exerciseTracker/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from . import views
from django.conf.urls import url

app_name = 'main'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^exercises/$', views.exercises, name='exercises'),
    url(r'^add_exercise/$', views.add_exercise, name='add_exercise'),
    url(r'^exercise_entries/$', views.exercise_entries, name='exercise_entries'),
    url(r'^add_exercise_entry/(?P<pk>[0-9]+)/$', views.add_exercise_entry, name='add_exercise_entry'),
    url(r'^add_exercise_focus/$', views.add_exercise_focus, name='add_exercise_focus'),
    url(r'^delete_exercise_focus/(?P<pk>[0-9]+)/$', views.delete_exercise_focus, name='delete_exercise_focus'),
    url(r'^delete_exercise/(?P<pk>[0-9]+)/$', views.delete_exercise, name='delete_exercise'),
    url(r'^exercise_focuses/$', views.exercise_focuses, name='exercise_focuses'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^today/$', views.today, name='today'),
    url(r'^exercise_detail/(?P<pk>[0-9]+)/$', views.exercise_detail, name='exercise_detail'),
    url(r'^help/$', views.help, name='help'),
    url(r'^routine/$', views.routine, name='routine'),
    url(r'^tomorrow/$', views.tomorrow, name='tomorrow'),
]

main/models.py
from django.db import models

class ExerciseFocus(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class CardioType(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Exercise(models.Model):
    name = models.CharField(max_length=100)
    exercise_focus = models.ForeignKey(ExerciseFocus, on_delete=models.CASCADE)
    
    laps = models.BooleanField()
    miles = models.BooleanField()
    reps = models.BooleanField()
    sets = models.BooleanField()
    time = models.BooleanField()
    weight = models.BooleanField()
    
    sunday = models.BooleanField()
    monday = models.BooleanField()
    tuesday = models.BooleanField()
    wednesday = models.BooleanField()
    thursday = models.BooleanField()
    friday = models.BooleanField()
    saturday = models.BooleanField()
    
    def __str__(self):
        return self.name
    
class ExerciseEntry(models.Model):
    date = models.DateField()
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    weight = models.FloatField(blank=True, null=True)
    
    miles = models.FloatField(blank=True, null=True)
    time = models.DurationField(blank=True, null=True)
    laps = models.IntegerField(blank=True, null=True)
    reps = models.IntegerField(blank=True, null=True)
    sets = models.IntegerField(blank=True, null=True)
    

# Create your models here.

main/views.py
from django.shortcuts import render, redirect
import requests
from .models import *
from datetime import datetime, timedelta
from django.db.models import Q

weekday_array = [
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday"]

def home(request):
    return render(request, 'main/home.html')
    
def help(request):
    return render(request, 'main/help.html')
    
def dashboard(request):
    
    focusesObj = ExerciseFocus.objects.all()
    exercisesObj = Exercise.objects.all()
    
    a = []
    
    for focus in focusesObj.order_by('name'):
        filtered_exercises = exercisesObj.filter(exercise_focus=focus).order_by('name')
        exercise_array = []
        for exercise in filtered_exercises:
            exercise_array += [exercise]
        a += [[focus,exercise_array]]
    
    x = {}
    x['var'] = a
    
    return render(request, 'main/dashboard.html', x)
    
def routine(request):
    
    exercisesObj = Exercise.objects.all()
    
    su,m,tu,w,th,f,sa = [],[],[],[],[],[],[]
    
    for exercise in exercisesObj:
        if exercise.sunday is True:
            su += [exercise]
        if exercise.monday is True:
            m += [exercise]
        if exercise.tuesday is True:
            tu += [exercise]
        if exercise.wednesday is True:
            w += [exercise]
        if exercise.thursday is True:
            th += [exercise]
        if exercise.friday is True:
            f += [exercise]
        if exercise.saturday is True:
            sa += [exercise]
            
            
    
    array = [
        [weekday_array[6].capitalize(),su],
        [weekday_array[0].capitalize(),m],
        [weekday_array[1].capitalize(),tu],
        [weekday_array[2].capitalize(),w],
        [weekday_array[3].capitalize(),th],
        [weekday_array[4].capitalize(),f],
        [weekday_array[5].capitalize(),sa]]
        
        
    x = {}
    x['array'] = array
    return render(request, 'main/routine.html', x)
    
def today(request):
    today = datetime.now().date()
    if request.method == 'POST':
        pass
        certain_exercise_id = request.POST.get('exercise_id') 
        certain_exercise = Exercise.objects.get(id=certain_exercise_id)
        
        attribute_d = {
            'date': today,
            'exercise': certain_exercise
        }
        
        if certain_exercise.weight:
            w = float(request.POST.get('weight'))
            attribute_d['weight'] =  w
        if certain_exercise.miles:
            m = float(request.POST.get('miles'))
            attribute_d['miles'] =  m
        if certain_exercise.time:
            hours = int(request.POST.get('hours'))
            minutes = int(request.POST.get('minutes'))
            seconds = int(request.POST.get('seconds'))
            t = timedelta(hours=hours, minutes=minutes, seconds=seconds)
            
            attribute_d['time'] =  t
        if certain_exercise.laps:
            l = int(request.POST.get('laps'))
            attribute_d['laps'] = l
        if certain_exercise.reps:
            r = int(request.POST.get('reps'))
            attribute_d['reps'] =  r
        if certain_exercise.sets:
            s = int(request.POST.get('sets'))
            attribute_d['sets'] =  s
            
        ExerciseEntry.objects.create(**attribute_d)
        
        return redirect('main:today')
    else:
        today_weekday = weekday_array[today.weekday()]
        all_focuses = ExerciseFocus.objects.all()
        all_exercises = Exercise.objects.all()
        l = []
        
        for focus in all_focuses:
            filtered_exercises = all_exercises.filter(
                Q(**{today_weekday: True}) & Q(exercise_focus=focus))
            exercise_l = []
            
            for exercise in filtered_exercises:
                entries_done_today = ExerciseEntry.objects.filter(
                    date=today,
                    exercise = exercise,)
                
                if len(entries_done_today) != 0:
                    doneToday = True
                else:
                    doneToday = False
                    
                exercise_l += [[exercise,doneToday]]
                
            if len(exercise_l) != 0:
                l += [[focus,exercise_l]]
        x = {}
        x['today_weekday'] = today_weekday.capitalize()
        x['var'] = l
        return render(request, 'main/today.html', x)
    
# def OLD_today(request):
#     today = datetime.now().date()
#     today_weekday = weekday_array[today.weekday()]
#     filter_dict = {today_weekday: True}
    
#     focusesObj = ExerciseFocus.objects.all()
#     exercisesObj = Exercise.objects.all()
    
#     array = []
    
#     for focus in focusesObj:
#         filtered_exercises = Exercise.objects.filter(exercise_focus=focus)
#         filtered_exercises = filtered_exercises.filter(**filter_dict)
#         exercise_array = []
#         for exercise in filtered_exercises:
#             doneToday = False
            
#             entries_done_today = ExerciseEntry.objects.filter(
#                 date=today,
#                 exercise=exercise)
#             print(entries_done_today)
                
#             if len(entries_done_today) is not 0:
#                 doneToday = True
                
#             exercise_array += [[exercise,doneToday]]
#         if len(exercise_array) is not 0:
#             array += [[focus,exercise_array]]
#     x = {}
#     x['today_weekday'] = today_weekday.capitalize()
#     x['var'] = array
#     return render(request, 'main/today.html', x)
            
#     if request.method == "POST":
#         e_id = request.POST.get('exercise_id') 
#         exerciseObj = Exercise.objects.get(id=e_id)
        
#         if exerciseObj.weight_involved:
#             w = request.POST.get('weight')
            
#             ExerciseEntry.objects.create(
#                 date = today,
#                 exercise = exerciseObj,
#                 weight = w)
#                 # this works!
#         elif exerciseObj.cardio_type:
#             if exerciseObj.cardio_type.name == "Miles and Time":
#                 m = request.POST.get('miles')
#                 t = request.POST.get('time')
                
#                 ExerciseEntry.objects.create(
#                     date = today,
#                     exercise = exerciseObj,
#                     miles = m,
#                     time = timedelta(hours=int(t)))
#                     # so far so good, still need to change timedelta
                    
#             elif exerciseObj.cardio_type.name == "Reps and Sets":
#                 r = request.POST.get('reps')
#                 s = request.POST.get('sets')
                
#                 ExerciseEntry.objects.create(
#                     date = today,
#                     exercise = exerciseObj,
#                     reps = r,
#                     sets = s)
                    
#             elif exerciseObj.cardio_type.name == "Swimming":
#                 t = request.POST.get('time')
#                 l = request.POST.get('laps')
                
#                 ExerciseEntry.objects.create(
#                     date = today,
#                     exercise = exerciseObj,
#                     time = timedelta(hours=int(t)),
#                     laps = l)
#         else:
#             ExerciseEntry.objects.create(
#                 date = today,
#                 exercise = exerciseObj)
            
#         return redirect('main:today')
#     else:
#         today = datetime.now().date()
#         today_weekday = weekday_array[today.weekday()]
#         filter_dict = {today_weekday: True}
        
#         focusesObj = ExerciseFocus.objects.all()
#         exercisesObj = Exercise.objects.all()
        
#         array = []
        
#         for focus in focusesObj:
#             filtered_exercises = Exercise.objects.filter(exercise_focus=focus)
#             filtered_exercises = filtered_exercises.filter(**filter_dict)
#             exercise_array = []
#             for exercise in filtered_exercises:
#                 doneToday = False
                
#                 entries_done_today = ExerciseEntry.objects.filter(
#                     date=today,
#                     exercise=exercise)
#                 print(entries_done_today)
                    
#                 if len(entries_done_today) is not 0:
#                     doneToday = True
                    
#                 exercise_array += [[exercise,doneToday]]
#             if len(exercise_array) is not 0:
#                 array += [[focus,exercise_array]]
#         x = {}
#         x['today_weekday'] = today_weekday.capitalize()
#         x['var'] = array
#         return render(request, 'main/today.html', x)
        
def tomorrow(request):
    tomorrow = datetime.now().date() + timedelta(days=1)
    tomorrow_weekday = weekday_array[tomorrow.weekday()]
    
    filter_dict = {tomorrow_weekday: True}
    
    tomorrow_exercises = Exercise.objects.filter(**filter_dict)
    
    x = {}
    x['tomorrow_weekday'] = tomorrow_weekday.capitalize()
    x['tomorrow_exercises'] = tomorrow_exercises
    return render(request, 'main/tomorrow.html', x)
    
    
    
    
#==================================================================

def exercise_focuses(request):
    x = {}
    x['exercise_focuses'] = ExerciseFocus.objects.all().order_by('name')
    return render(request, 'main/exercise_focuses.html', x)

def add_exercise_focus(request):
    if request.method == "POST":
        n = request.POST.get('name')
        
        ExerciseFocus.objects.create(
            name = n)
            
        return redirect('main:exercise_focuses')
    else:
        return render(request, 'main/add_exercise_focus.html')

def delete_exercise_focus(request, pk):
    if request.method == "POST":
        ExerciseFocus.objects.get(pk=pk).delete()

main/templates/main/add_exercise.html
{% extends 'main/base.html' %}

{% block title %}Add Exercise{% endblock %}

{% block body %}
<div class="col-sm-12">
    <form role="form" action="{% url 'main:add_exercise' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" name="name" placeholder="Enter name">
        </div>
        
        <div class="form-group">
            <label for="exercise_focus">Focus <a href="{% url 'main:add_exercise_focus' %}">(Add New)</a></label>
            <select class="form-control" name="exercise_focus">
                {% for exercise_focus in exercise_focuses %}
                <option>{{exercise_focus}}</option>
                {% endfor %}
            </select>
        </div>
        
        <div class="form-group form-check">
            <h1>Attributes</h1>
            
            <input type="checkbox" class="form-check-input" name="laps">
            <label class="form-check-label" for="laps">laps</label>
            <br>
            
            <input type="checkbox" class="form-check-input" name="miles">
            <label class="form-check-label" for="miles">miles</label>
            <br>
            
            <input type="checkbox" class="form-check-input" name="reps">
            <label class="form-check-label" for="reps">reps</label>
            <br>
            
            <input type="checkbox" class="form-check-input" name="sets">
            <label class="form-check-label" for="sets">sets</label>
            <br>
            
            <input type="checkbox" class="form-check-input" name="time">
            <label class="form-check-label" for="time">time</label>
            <br>
            
            <input type="checkbox" class="form-check-input" name="weight">
            <label class="form-check-label" for="weight">weight</label>
            <br>
    
        </div>
        
        <div class="form-group form-check">
            <h1>Routine Days</h1>
            <input type="checkbox" class="form-check-input" name="sunday">
            <label class="form-check-label" for="weight_involved">Sunday</label>
            <br>
            <input type="checkbox" class="form-check-input" name="monday">
            <label class="form-check-label" for="weight_involved">Monday</label>
            <br>
            <input type="checkbox" class="form-check-input" name="tuesday">
            <label class="form-check-label" for="weight_involved">Tuesday</label>
            <br>
            <input type="checkbox" class="form-check-input" name="wednesday">
            <label class="form-check-label" for="weight_involved">Wednesday</label>
            <br>
            <input type="checkbox" class="form-check-input" name="thursday">
            <label class="form-check-label" for="weight_involved">Thursday</label>
            <br>
            <input type="checkbox" class="form-check-input" name="friday">
            <label class="form-check-label" for="weight_involved">Friday</label>
            <br>
            <input type="checkbox" class="form-check-input" name="saturday">
            <label class="form-check-label" for="weight_involved">Saturday</label>
        </div>
        
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

main/templates/main/add_exercise_entry.html
{% extends 'main/base.html' %}

{% block title %}Add Exercise Entry{% endblock %}

{% block body %}
<div class="col-sm-12">
    <h1>Adding entry for {{exercise}}</h1>
    <form role="form" action="{% url 'main:add_exercise_entry' pk=exercise.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="date">Date</label>
            <input type="date" class="form-control" name="date" value="{{today_date}}">
        </div>
        
        {% if exercise.weight_involved %}
        <div class="form-group">
            <label for="weight">Weight</label>
            <input type="number" class="form-control" name="weight" required>
        </div>
        {% else %}
        <div class="form-group">
            <input type="hidden" class="form-control" name="weight" value=-1>
        </div>
        {% endif %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

main/templates/main/add_exercise_focus.html
{% extends 'main/base.html' %}

{% block title %}Add Exercise Focus{% endblock %}

{% block body %}
<div class="col-sm-12">
    <form role="form" action="{% url 'main:add_exercise_focus' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" name="name" placeholder="Enter name">
        </div>
        
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <!--allow subtemplates to set page title-->
            <title>{% block title %}{% endblock %}</title>
            {% load staticfiles %}
            <!--set website icon-->
            <link rel="icon" type="image/png" href="#"/>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
            <!--<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>-->
            
            
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
            <meta name="viewport" content = "width=device-width, initial-scale=1.0">
            <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>-->
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <style type="text/css">
              body{
                  background-color: black;
                  color: white;
              }
              {% block css %}
              {% endblock %}
            </style>
        </head>
        <body>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <a href="{% url 'main:home' %}"><h1>Home</h1></a>
                        <br>
                    </div>
                    {% block body %}
                    {% endblock %}
                </div>
            </div>
            
        </body>
    </html>

main/templates/main/dashboard.html
{% extends 'main/base.html' %}

{% block title %}Dashboard{% endblock %}

{% block body %}
<div class="col-sm-12">
    {% for focus_array in var %}
    
    <h1>{{focus_array.0}}</h1>
    {% for exercise in focus_array.1 %}
    <h4><a href="{% url 'main:exercise_detail' pk=exercise.pk %}">{{exercise}}</a> <a href="{% url 'main:add_exercise_entry' pk=exercise.pk %}">add entry</a></h4>
    {% endfor %}
    
    
    {% endfor %}
</div>
{% endblock %}

main/templates/main/delete_exercise.html
{% extends 'main/base.html' %}

{% block title %}Delete Exercise{% endblock %}

{% block body %}
<div class="col-sm-12">
    <h1>Are you sure that you want to delete {{certain_exercise}}?</h1>
    <form role="form" action="{% url 'main:delete_exercise' pk=certain_pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Yes</button>
            <button type="button" class="btn btn-primary" onclick="window.history.go(-1)">No</button>
        </div>
    </form>
</div>
{% endblock %}

main/templates/main/delete_exercise_focus.html
{% extends 'main/base.html' %}

{% block title %}Delete Exercise Focus{% endblock %}

{% block body %}
<div class="col-sm-12">
    <h1>Are you sure that you want to delete {{certain_exercise_focus}}?</h1>
    <form role="form" action="{% url 'main:delete_exercise_focus' pk=certain_pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Yes</button>
            <button type="button" class="btn btn-primary" onclick="window.history.go(-1)">NO</button>
            
        </div>
        
        
        
        
    </form>
</div>
{% endblock %}

main/templates/main/delete_focus.html
{% extends 'main/base.html' %}

{% block title %}Delete Focus{% endblock %}

{% block body %}
<div class="col-sm-12">
    <h1>Are you sure that you want to delete {{certain_focus}}?</h1>
    <form role="form" action="{% url 'main:delete_focus' pk=certain_pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Yes</button>
            <button type="button" class="btn btn-primary" onclick="window.history.go(-1)">NO</button>
            
        </div>
        
        
        
        
    </form>
</div>
{% endblock %}

main/templates/main/exercise_detail.html
{% extends 'main/base.html' %}

{% block title %}Exercise Detail{% endblock %}

{% block css %}
{% endblock %}

{% block body %}
<div class="col-sm-12">
    <h1>{{certain_exercise.name}}</h1>
</div>

{% if not chart_empty %}
<div class="col-sm-12" id="chart">
  <script>
      var chart_array = {{chart_data|safe}}
      var chart_title = '{{chart_title|safe}}'
  </script>
  <script type="text/javascript">
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawChart);
  
    function drawChart() {
      var data = google.visualization.arrayToDataTable(chart_array);
  
      var options = {
        title: chart_title,
        hAxis: {title: 'Date',  titleTextStyle: {color: '#333'}},
        vAxis: {minValue: 0}
      };
  
      var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
      chart.draw(data, options);
    }
    
    $(window).resize(function(){
      drawChart();
    });
  </script>
  <div id="chart_div"></div>
</div>
{% else %}
<div class="col-sm-12">
  <h1>No data found for this exercise</h1>
</div>
{% endif %}


{% endblock %}

main/templates/main/exercise_entries.html
{% extends 'main/base.html' %}

{% block title %}Exercise Entries{% endblock %}

{% block body %}
<div class="col-sm-12">
    {% for exercise in exercise_entries %}
    <h1>{{exercise}}</h1>
    {% endfor %}
</div>
{% endblock %}

main/templates/main/exercise_focuses.html
{% extends 'main/base.html' %}

{% block title %}Exercise Focuses{% endblock %}

{% block body %}
<div class="col-sm-12">
    <a href="{% url 'main:add_exercise_focus' %}"><h1>Add New Exercise Focus</h1></a>
    {% for exercise_focus in exercise_focuses %}
    <h1>{{exercise_focus}} <a href="{% url 'main:delete_exercise_focus' pk=exercise_focus.pk %}">del</a></h1>
    {% endfor %}
</div>
{% endblock %}

main/templates/main/exercises.html
{% extends 'main/base.html' %}

{% block title %}Exercises{% endblock %}

{% block body %}
<div class="col-sm-12">
    <a href="{% url 'main:add_exercise' %}"><h1>Add New Exercise</h1></a>
    {% for exercise in exercises %}
    <h1><a href="{% url 'main:exercise_detail' pk=exercise.id %}">{{exercise}}</a> <a href="{% url 'main:delete_exercise' pk=exercise.pk %}">del</a></h1>
    {% endfor %}
</div>
{% endblock %}

main/templates/main/help.html
{% extends 'main/base.html' %}

{% block title %}Home{% endblock %}

{% block body %}
<div class="col-sm-12">
    <h1 style="font-weight:bold;">Help</h1>
    <br>
    <h2>What exercises should I add?</h2>
    <br>
    <p>Popular examples of exercises and focuses include the following:</p>
    <ul>
        <li>Focus: Abs
            <ul>
                <li>Crunches</li>
                <li>Seated Twists</li>
            </ul>
        </li>
        <li>Focus: Back
            <ul>
                <li>One Arm Dumbbell Rows</li>
                <li>Bent Over Barbell Rows</li>
            </ul>
        </li>
        <li>Focus: Biceps
            <ul>
                <li>Standing Barbell Curl</li>
                <li>Concentration Curls</li>
            </ul>
        </li>
        <li>Focus: Chest
            <ul>
                <li>Barbell Incline Bench Presses</li>
                <li>Flat Bench Dumbbell Fly</li>
            </ul>
        </li>
        <li>Focus: Legs
            <ul>
                <li>Barbell Squats</li>
                <li>Barbell Straight Leg Deadlift</li>
            </ul>
        </li>
        <li>Focus: Shoulders
            <ul>
                <li>Seated Dumbbell Presses</li>
                <li>Seated Lateral Raises</li>
            </ul>
        </li>
        <li>Focus: Triceps
            <ul>
                <li>Seated Overhead Dumbbell Extensions</li>
                <li>Lying Cross Face Triceps Extensions</li>
            </ul>
        </li>
    </ul>
</div>
{% endblock %}

main/templates/main/today.html
{% extends 'main/base.html' %}

{% block title %}Today{% endblock %}

{% block body %}
<div class="col-sm-12" style="border:white solid 2px;text-align:center;">
  <h1>{{today_weekday}}</h1>
  <br>
</div>

{% for a in var %}
<div class="col-sm-6" style="border:white solid 2px;text-align:center;">
  <h2>{{a.0}}</h2>
  {% for exercise in a.1 %}
    <a href="{% url 'main:exercise_detail' pk=exercise.0.id %}"><h5>{{exercise.0.name}}</h5></a>
    {% if not exercise.1 %}
    <form role="form" action="{% url 'main:today' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% if exercise.0.laps %}
        <div class="form-group">
          <label for="laps">Laps</label>
          <input type="number" class="form-control" name="laps" placeholder="Enter laps" min="0">
          <input type="hidden" class="form-control" name="exercise_id" value={{exercise.0.id}}>
        </div>
      {% endif %}
      {% if exercise.0.miles %}
        <div class="form-group">
          <label for="miles">Laps</label>
          <input type="number" class="form-control" name="miles" placeholder="Enter miles" min="0">
          <input type="hidden" class="form-control" name="exercise_id" value={{exercise.0.id}}>
        </div>
      {% endif %}
      {% if exercise.0.reps %}
        <div class="form-group">
          <label for="reps">Reps</label>
          <input type="number" class="form-control" name="reps" placeholder="Enter reps" min="0">
          <input type="hidden" class="form-control" name="exercise_id" value={{exercise.0.id}}>
        </div>
      {% endif %}
      {% if exercise.0.sets %}
        <div class="form-group">
          <label for="sets">Sets</label>
          <input type="number" class="form-control" name="sets" placeholder="Enter sets" min="0">
          <input type="hidden" class="form-control" name="exercise_id" value={{exercise.0.id}}>
        </div>
      {% endif %}
      {% if exercise.0.time %}
      <div class="form-row">
        <div class="form-group col-md-4">
          <label for="time">Hours</label>
          <input type="number" class="form-control" name="hours" placeholder="Enter hours" min="0" max = "23" value="0">
          <input type="hidden" class="form-control" name="exercise_id" value={{exercise.0.id}}>
        </div>
        <div class="form-group col-md-4">
          <label for="time">Minutes</label>
          <input type="number" class="form-control" name="minutes" placeholder="Enter minutes" min="0" max = "59" value="0">
          <input type="hidden" class="form-control" name="exercise_id" value={{exercise.0.id}}>
        </div>
        <div class="form-group col-md-4">
          <label for="time">Seconds</label>
          <input type="number" class="form-control" name="seconds" placeholder="Enter seconds" min="0" max = "59" value="0">
          <input type="hidden" class="form-control" name="exercise_id" value={{exercise.0.id}}>
        </div>
      </div>
      {% endif %}
      {% if exercise.0.weight %}
        <div class="form-group">
          <label for="weight">Weight</label>
          <input type="number" class="form-control" name="weight" placeholder="Enter weight" min="0">
          <input type="hidden" class="form-control" name="exercise_id" value={{exercise.0.id}}>
        </div>
      {% endif %}
        <button type="submit" class="btn btn-primary">Mark As Done</button>
      </form>
    {% else %}
    <button type="button" class="btn btn-success">Done</button>
    {% endif %}
  {% endfor %}
  <br>
</div>
{% endfor %}

{% endblock %}